on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE: ghcr.io/whitekr/discord-metrics

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      # tonistiigi/binfmt 이미지를 이용해 qemu 설치
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # docker buildx 설치
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

        # secrets를 이용해 Docker Hub 로그인
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      # buildx 명령어로 amd64, arm64, arm/v6, arm/v7 아키텍처 이미지 빌드 및
      - name: Docker Build
        run: docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.DOCKER_IMAGE }}:latest -t ${{ env.DOCKER_IMAGE }}:${{ github.run_id }} --push .
